import { Hono } from 'hono'
import { promises as fs } from 'node:fs'
import path from 'node:path'
import {
  readConfig,
  writeConfig,
  toPublicConfig,
  validateObsidianPath,
  type StoredConfig,
  type CaptureMode,
  type ReminderMode,
} from '../config-store.js'

const onboarding = new Hono()

// GET /api/config — returns current onboarding state
onboarding.get('/api/config', async (c) => {
  const config = readConfig()
  // If no obsidianPath and captureMode is still default, treat as not onboarded
  const isOnboarded = config.captureMode !== undefined &&
    // check a marker file instead of checking obsidianPath to handle textbox/hana modes
    await fs.access(path.join(require('os').homedir(), '.lifemaxxing', 'config.json'))
      .then(() => true)
      .catch(() => false)

  return c.json({ ...toPublicConfig(config), onboarded: isOnboarded })
})

// POST /api/config — save onboarding responses
onboarding.post('/api/config', async (c) => {
  const body = await c.req.json<{
    captureMode: CaptureMode
    obsidianPath?: string
    reminderMode: ReminderMode
    reminderTime?: string
    winDefinitions?: Record<string, string>
    timezone?: string
  }>()

  // Validate obsidian path if provided
  if (body.captureMode === 'obsidian' && body.obsidianPath?.trim()) {
    const check = await validateObsidianPath(body.obsidianPath.trim())
    if (!check.ok) return c.json({ error: check.reason }, 400)

    // Create the WinCalendar subfolder if it doesn't exist
    const winDir = path.join(body.obsidianPath.trim(), 'WinCalendar')
    await fs.mkdir(winDir, { recursive: true })

    // Create empty timeline file if it doesn't exist
    const timelinePath = path.join(winDir, 'timeline-life.md')
    try {
      await fs.access(timelinePath)
    } catch {
      await fs.writeFile(
        timelinePath,
        '# Life Timeline\n*Generated by lifemaxxing. Edit freely; the app parses `## <Date> — <Title>` headings.*\n\n',
        'utf-8'
      )
    }
  }

  const config: StoredConfig = {
    captureMode: body.captureMode,
    obsidianPath: body.obsidianPath?.trim() ?? '',
    reminderMode: body.reminderMode,
    reminderTime: body.reminderTime ?? '21:00',
    timezone: body.timezone ?? Intl.DateTimeFormat().resolvedOptions().timeZone,
    winDefinitions: body.winDefinitions ?? {},
  }

  await writeConfig(config)

  return c.json({ ...toPublicConfig(config), onboarded: true })
})

export default onboarding
