import { Hono } from 'hono'
import { promises as fs } from 'node:fs'
import path from 'node:path'
import os from 'node:os'
import {
  readConfig,
  writeConfig,
  toPublicConfig,
  validateObsidianPath,
  type StoredConfig,
  type CaptureMode,
  type ReminderMode,
} from '../config-store.js'

const onboarding = new Hono()

// GET /api/config — returns current onboarding state
// Bug 5 fix: onboarded = config file actually exists and is valid
onboarding.get('/api/config', (c) => {
  const config = readConfig()
  if (!config) return c.json({ onboarded: false })
  return c.json(toPublicConfig(config))
})

// POST /api/config — save onboarding responses
onboarding.post('/api/config', async (c) => {
  const body = await c.req.json<{
    captureMode: CaptureMode
    obsidianPath?: string
    reminderMode: ReminderMode
    reminderTime?: string
    winDefinitions?: Record<string, string>
    timezone?: string
  }>()

  // Validate obsidian path if provided
  if (body.captureMode === 'obsidian' && body.obsidianPath?.trim()) {
    const check = await validateObsidianPath(body.obsidianPath.trim())
    if (!check.ok) return c.json({ error: check.reason }, 400)

    // Create WinCalendar subfolder + empty timeline if missing
    const winDir = path.join(body.obsidianPath.trim(), 'WinCalendar')
    await fs.mkdir(winDir, { recursive: true })
    const timelinePath = path.join(winDir, 'timeline-life.md')
    try {
      await fs.access(timelinePath)
    } catch {
      await fs.writeFile(
        timelinePath,
        '# Life Timeline\n*Generated by lifemaxxing. Edit freely; the app parses `## <Date> — <Title>` headings.*\n\n',
        'utf-8',
      )
    }
  }

  // For textbox/hana modes, use a local storage path
  const localStoragePath = path.join(os.homedir(), '.lifemaxxing', 'timeline-life.md')
  if (body.captureMode !== 'obsidian') {
    await fs.mkdir(path.dirname(localStoragePath), { recursive: true })
    try { await fs.access(localStoragePath) } catch {
      await fs.writeFile(
        localStoragePath,
        '# Life Timeline\n*Generated by lifemaxxing.*\n\n',
        'utf-8',
      )
    }
  }

  const config: StoredConfig = {
    captureMode: body.captureMode,
    obsidianPath: body.captureMode === 'obsidian'
      ? (body.obsidianPath?.trim() ?? '')
      : path.dirname(localStoragePath),  // point at ~/.lifemaxxing for textbox/hana
    reminderMode: body.reminderMode,
    reminderTime: body.reminderTime ?? '21:00',
    timezone: body.timezone ?? Intl.DateTimeFormat().resolvedOptions().timeZone,
    winDefinitions: body.winDefinitions ?? {},
  }

  await writeConfig(config)
  return c.json(toPublicConfig(config))
})

export default onboarding
