import { Hono } from 'hono'
import { promises as fs } from 'node:fs'
import path from 'node:path'
import os from 'node:os'
import {
  readConfig,
  writeConfig,
  toPublicConfig,
  toPublicConfigUnonboarded,
  validateObsidianPath,
  type StoredConfig,
  type CaptureMode,
  type ReminderMode,
} from '../config-store.js'
import {
  LIFE_AREA_KEYS,
  type LifeAreaKey,
} from '../default-win-definitions.js'

const onboarding = new Hono()

type ConfigUpsertBody = {
  captureMode?: CaptureMode
  obsidianPath?: string
  reminderMode?: ReminderMode
  reminderTime?: string
  winDefinitions?: Record<string, string>
  timezone?: string
}

async function ensureVaultFiles(config: StoredConfig): Promise<void> {
  if (config.captureMode === 'obsidian' && config.obsidianPath?.trim()) {
    const winDir = path.join(config.obsidianPath.trim(), 'WinCalendar')
    await fs.mkdir(winDir, { recursive: true })
    const timelinePath = path.join(winDir, 'timeline-life.md')
    try {
      await fs.access(timelinePath)
    } catch {
      await fs.writeFile(
        timelinePath,
        '# Life Timeline\n*Generated by lifemaxxing. Edit freely; the app parses `## <Date> — <Title>` headings.*\n\n',
        'utf-8',
      )
    }
  }

  const localStoragePath = path.join(os.homedir(), '.lifemaxxing', 'timeline-life.md')
  if (config.captureMode !== 'obsidian') {
    await fs.mkdir(path.dirname(localStoragePath), { recursive: true })
    try {
      await fs.access(localStoragePath)
    } catch {
      await fs.writeFile(
        localStoragePath,
        '# Life Timeline\n*Generated by lifemaxxing.*\n\n',
        'utf-8',
      )
    }
  }
}

function mergeWinDefinitionOverrides(
  prev: Record<string, string>,
  patch: Record<string, string> | undefined,
): Record<string, string> {
  if (!patch) return { ...prev }
  const next = { ...prev }
  for (const [k, v] of Object.entries(patch)) {
    if (!LIFE_AREA_KEYS.includes(k as LifeAreaKey)) continue
    if (v === undefined) continue
    const t = String(v).trim()
    if (t === '') delete next[k]
    else next[k] = t
  }
  return next
}

function storedFromPostBody(body: {
  captureMode: CaptureMode
  obsidianPath?: string
  reminderMode: ReminderMode
  reminderTime?: string
  winDefinitions?: Record<string, string>
  timezone?: string
}): StoredConfig {
  const localStoragePath = path.join(os.homedir(), '.lifemaxxing', 'timeline-life.md')
  return {
    captureMode: body.captureMode,
    obsidianPath:
      body.captureMode === 'obsidian'
        ? (body.obsidianPath?.trim() ?? '')
        : path.dirname(localStoragePath),
    reminderMode: body.reminderMode,
    reminderTime: body.reminderTime ?? '21:00',
    timezone: body.timezone ?? Intl.DateTimeFormat().resolvedOptions().timeZone,
    winDefinitions: body.winDefinitions ?? {},
  }
}

function mergePatchIntoStored(prev: StoredConfig, patch: ConfigUpsertBody): StoredConfig {
  const localStoragePath = path.join(os.homedir(), '.lifemaxxing', 'timeline-life.md')
  const nextCapture = patch.captureMode ?? prev.captureMode
  let nextPath = prev.obsidianPath
  if (patch.obsidianPath !== undefined) {
    nextPath = patch.obsidianPath.trim()
  }
  if (nextCapture !== 'obsidian') {
    nextPath = path.dirname(localStoragePath)
  }
  return {
    captureMode: nextCapture,
    obsidianPath: nextPath,
    reminderMode: patch.reminderMode ?? prev.reminderMode,
    reminderTime: patch.reminderTime ?? prev.reminderTime,
    timezone: patch.timezone ?? prev.timezone,
    winDefinitions: mergeWinDefinitionOverrides(prev.winDefinitions ?? {}, patch.winDefinitions),
  }
}

// GET /api/config
onboarding.get('/api/config', (c) => {
  const config = readConfig()
  if (!config) return c.json(toPublicConfigUnonboarded())
  return c.json(toPublicConfig(config))
})

// POST /api/config — full replace (initial onboarding payload)
onboarding.post('/api/config', async (c) => {
  const body = await c.req.json<{
    captureMode: CaptureMode
    obsidianPath?: string
    reminderMode: ReminderMode
    reminderTime?: string
    winDefinitions?: Record<string, string>
    timezone?: string
  }>()

  if (body.captureMode === 'obsidian' && body.obsidianPath?.trim()) {
    const check = await validateObsidianPath(body.obsidianPath.trim())
    if (!check.ok) return c.json({ error: check.reason }, 400)
  }

  const config = storedFromPostBody(body)

  await ensureVaultFiles(config)
  await writeConfig(config)
  return c.json(toPublicConfig(config))
})

// PATCH /api/config — partial update (same fields as POST, all optional)
onboarding.patch('/api/config', async (c) => {
  const prev = readConfig()
  if (!prev) return c.json({ error: 'No profile yet.' }, 400)

  const patch = await c.req.json<ConfigUpsertBody>()
  const merged = mergePatchIntoStored(prev, patch)

  if (merged.captureMode === 'obsidian' && merged.obsidianPath?.trim()) {
    const check = await validateObsidianPath(merged.obsidianPath.trim())
    if (!check.ok) return c.json({ error: check.reason }, 400)
  }

  await ensureVaultFiles(merged)
  await writeConfig(merged)
  return c.json(toPublicConfig(merged))
})

export default onboarding
