import { promises as fs } from 'node:fs'
import path from 'node:path'

const WIN_SUBFOLDER = 'WinCalendar'
const TIMELINE_FILENAME = 'timeline-life.md'

function winCalendarDir(obsidianPath: string): string {
  return path.join(obsidianPath, WIN_SUBFOLDER)
}

export function timelinePath(obsidianPath: string): string {
  return path.join(winCalendarDir(obsidianPath), TIMELINE_FILENAME)
}

export async function ensureVaultLayout(obsidianPath: string): Promise<void> {
  await fs.mkdir(winCalendarDir(obsidianPath), { recursive: true })
  const tl = timelinePath(obsidianPath)
  try {
    await fs.access(tl)
  } catch {
    await fs.writeFile(
      tl,
      '# Life Timeline\n*Generated by lifemaxxing. Edit freely; the app parses `## <Date> — <Title>` headings.*\n\n---\n\n',
      'utf8',
    )
  }
}

export async function readTimeline(obsidianPath: string): Promise<string> {
  try {
    return await fs.readFile(timelinePath(obsidianPath), 'utf8')
  } catch (err: unknown) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return ''
    throw err
  }
}

/**
 * Appends a single win as a minimal markdown block.
 * Format: ## Mon DD, YYYY — Title\narea: X\n**What happened:** …\n\n---\n\n
 */
export async function appendWinToTimeline(
  obsidianPath: string,
  win: { date: string; title: string; areas: string[]; body?: string },
): Promise<void> {
  await ensureVaultLayout(obsidianPath)
  const [yearStr, monthStr, dayStr] = win.date.split('-')
  const monthNames = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
  const monthName = monthNames[Number(monthStr) - 1] ?? monthStr
  const heading = `## ${monthName} ${Number(dayStr)}, ${yearStr} — ${win.title}`
  const areaLine = win.areas.length > 0 ? `area: ${win.areas.join(', ')}\n` : ''
  const bodyLine = win.body ? `**What happened:** ${win.body.trim()}\n` : ''
  const block = `${heading}\n${areaLine}${bodyLine}\n---\n\n`

  const target = timelinePath(obsidianPath)
  let existing = ''
  try { existing = await fs.readFile(target, 'utf8') } catch { /* new file */ }
  const next = (existing.trimEnd() + '\n\n' + block).trimStart()
  await fs.writeFile(target, next, 'utf8')
}
