import { promises as fs } from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { parseTimelineMarkdown } from './timeline-parser.js'

const WIN_SUBFOLDER = 'WinCalendar'
const TIMELINE_FILENAME = 'timeline-life.md'

/** Per-win reveal times (UTC ISO strings). Omit a win id meaning "visible immediately". */
const revealStatePath = () =>
  path.join(os.homedir(), '.lifemaxxing', 'reveal-at.json')

function splitTimelineSections(markdown: string): { preamble: string; sections: string[] } {
  const parts = markdown.split(/\n(?=## )/)
  if (parts.length === 0) return { preamble: '', sections: [] }
  const first = parts[0]
  if (parts.length === 1 && first.startsWith('## ')) {
    return { preamble: '', sections: [first] }
  }
  return { preamble: first, sections: parts.slice(1) }
}

function joinTimelineSections(preamble: string, sections: string[]): string {
  if (sections.length === 0) return preamble
  if (!preamble) return sections.join('\n')
  return `${preamble}\n${sections.join('\n')}`
}

function sectionContainsWinId(section: string, winId: string): boolean {
  const byDate = parseTimelineMarkdown(section.startsWith('## ') ? section : `## ${section}`)
  return Object.values(byDate).some((wins) => wins.some((w) => w.id === winId))
}

function replaceAreaLineInSection(section: string, areas: readonly string[]): string {
  const s = section.replace(/\s+$/, '')
  const nl = s.indexOf('\n')
  if (nl === -1) {
    return `${s}\narea: ${areas.join(', ')}\n`
  }
  const head = s.slice(0, nl)
  let rest = s.slice(nl + 1)
  const replacement = `area: ${areas.join(', ')}`
  if (/^area:\s*.+$/im.test(rest)) {
    rest = rest.replace(/^area:\s*.+$/im, replacement)
  } else {
    rest = `${replacement}\n${rest}`
  }
  return `${head}\n${rest}\n`
}

function winCalendarDir(obsidianPath: string): string {
  return path.join(obsidianPath, WIN_SUBFOLDER)
}

export function timelinePath(obsidianPath: string): string {
  return path.join(winCalendarDir(obsidianPath), TIMELINE_FILENAME)
}

export async function ensureVaultLayout(obsidianPath: string): Promise<void> {
  await fs.mkdir(winCalendarDir(obsidianPath), { recursive: true })
  const tl = timelinePath(obsidianPath)
  try {
    await fs.access(tl)
  } catch {
    await fs.writeFile(
      tl,
      '# Life Timeline\n*Generated by lifemaxxing. Edit freely; the app parses `## <Date> — <Title>` headings.*\n\n---\n\n',
      'utf8',
    )
  }
}

export async function readTimeline(obsidianPath: string): Promise<string> {
  try {
    return await fs.readFile(timelinePath(obsidianPath), 'utf8')
  } catch (err: unknown) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return ''
    throw err
  }
}

export async function getRevealAtMap(_vaultPath: string): Promise<Record<string, string>> {
  try {
    const raw = await fs.readFile(revealStatePath(), 'utf8')
    const data = JSON.parse(raw) as unknown
    if (!data || typeof data !== 'object' || Array.isArray(data)) return {}
    const out: Record<string, string> = {}
    for (const [k, v] of Object.entries(data)) {
      if (typeof v === 'string') out[k] = v
    }
    return out
  } catch {
    return {}
  }
}

/** Replace the timeline win block identified by stable id (`YYYY-MM-DD-slug`). */
export async function updateWinAreasInFile(
  timelineFileAbsPath: string,
  winId: string,
  newAreas: readonly string[],
): Promise<boolean> {
  let markdown: string
  try {
    markdown = await fs.readFile(timelineFileAbsPath, 'utf8')
  } catch {
    return false
  }

  const { preamble, sections } = splitTimelineSections(markdown)
  let found = false
  const nextSections = sections.map((sec) => {
    if (!sectionContainsWinId(sec, winId)) return sec
    found = true
    return replaceAreaLineInSection(sec, newAreas)
  })
  if (!found) return false

  await fs.writeFile(timelineFileAbsPath, joinTimelineSections(preamble, nextSections), 'utf8')
  return true
}

export async function deleteWin(obsidianPath: string, winId: string): Promise<void> {
  const file = timelinePath(obsidianPath)
  let markdown: string
  try {
    markdown = await fs.readFile(file, 'utf8')
  } catch {
    return
  }
  const { preamble, sections } = splitTimelineSections(markdown)
  const kept = sections.filter((sec) => !sectionContainsWinId(sec, winId))
  if (kept.length === sections.length) return
  await fs.writeFile(file, joinTimelineSections(preamble, kept), 'utf8')
}

/**
 * Appends a single win as a minimal markdown block.
 * Format: ## Mon DD, YYYY — Title\narea: X\n**What happened:** …\n\n---\n\n
 */
export async function appendWinToTimeline(
  obsidianPath: string,
  win: { date: string; title: string; areas: string[]; body?: string },
): Promise<void> {
  await ensureVaultLayout(obsidianPath)
  const [yearStr, monthStr, dayStr] = win.date.split('-')
  const monthNames = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
  const monthName = monthNames[Number(monthStr) - 1] ?? monthStr
  const heading = `## ${monthName} ${Number(dayStr)}, ${yearStr} — ${win.title}`
  const areaLine = win.areas.length > 0 ? `area: ${win.areas.join(', ')}\n` : ''
  const bodyLine = win.body ? `**What happened:** ${win.body.trim()}\n` : ''
  const block = `${heading}\n${areaLine}${bodyLine}\n---\n\n`

  const target = timelinePath(obsidianPath)
  let existing = ''
  try { existing = await fs.readFile(target, 'utf8') } catch { /* new file */ }
  const next = (existing.trimEnd() + '\n\n' + block).trimStart()
  await fs.writeFile(target, next, 'utf8')
}
